name: Terraform Destroy
run-name: Running Terraform Destroy by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      env_select:
        description: "Select the environment to configure: "
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  Terraform-Destroy:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform workspace new environment and select
        run: |
          terraform workspace select "${{ github.event.inputs.env_select }}" 2>/dev/null || terraform workspace new "${{ github.event.inputs.env_select }}"
          terraform workspace list

      - name: Terraform Destroy
        run: terraform destroy -no-color -auto-approve -var-file="./${{ github.event.inputs.env_select }}.tfvars"

  Terraform_Destroy_Status_Summary:
    needs: [Terraform-Destroy]
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          TF_STATUS=${{ needs.Terraform-Destroy.outputs.status }}

          echo '## 🚀 Preparing Build Summary 🚀' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo "| Job Name        | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| tf-destroy      | $TF_STATUS |" >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY

          echo '## Job ran by: ${{ github.actor }}' >> $GITHUB_STEP_SUMMARY
